### ISSUE TITLE
Search by sample on worksheets page

### ISSUE THREAD

**Issue by erikwaskiewicz** [AWGL/somatic_db#11]

**Comment by erikwaskiewicz** [comment]
Also add DNA/ RNA column, and limit results to most recent x number of runs, with button to expand to all results

**Comment by LauraMcCluskey** [comment]
DNA/RNA column added

**Comment by LauraMcCluskey** [comment]
Now able to sort by values in datatable (e.g runid, worksheetid) but still need to add functionality to sort by sampleid

**Comment by Istaisa** [comment]
Added ability to search by sample id to the main worklist page.

**Comment by erikwaskiewicz** [comment]
fixed in #57, may be a bit slow so we'll need to monitor over the next few weeks
