### ISSUE TITLE
Coverage summary CSV for whole worksheet

### ISSUE THREAD

**Issue by erikwaskiewicz** [AWGL/somatic_db#110]
Where there is suboptimal coverage the scientists click into each sample and check the gene coverage to decide if the whole run should be repeated, which takes a while and is clunky

We can add a button to the bottom of the worksheets page to download a CSV for gene coverage of all samples on the worksheet so that it can be checked quickly in future

**Comment by niamhat** [comment]
Closed by https://github.com/AWGL/somatic_db/pull/127
