### ISSUE TITLE
Gnomad link format has changed

### ISSUE THREAD

**Issue by erikwaskiewicz** [AWGL/somatic_db#78]
Build 37 links now take you to a build 38 variant, need to change the link here - 

https://github.com/AWGL/somatic_db/blob/87c5238e72da38d9a4790c97e235ad91c5caa1df/analysis/templates/analysis/analysis-snvs.html#L78

to `https://gnomad.broadinstitute.org/variant/{{ v.genomic }}?dataset=gnomad_r2_1`

**Comment by PatrickWeller** [comment]
Link format has changed again! :( 

SVD links out to:
![image](https://github.com/user-attachments/assets/d1005e4b-79a8-4a4c-846f-be1162115fb5)

But actual link would be more like:
![image](https://github.com/user-attachments/assets/29c50720-0fff-4d6a-be14-1dd9f44529e7)
