### ISSUE TITLE
Add Unit testing to check whether samples are uploaded to database

### ISSUE THREAD

**Issue by niamhat** [AWGL/somatic_db#87]
For AE-23-273-GEN

**Comment by erikwaskiewicz** [comment]
Also add a check for fusion imports that the input is sanitised correctly, see #97 
I've updated the test data so will need to be pulled into any existing branch, now there are two RET calls in the test data with dodgy inputs, NCOA4/RET and CCDC6--RET, these should be sanitsed to NCOA4-RET and CCDC6-RET. These are included for both TSO500 RNA and ctDNA
