### ISSUE TITLE
Ability to reopen a case

### ISSUE THREAD

**Issue by erikwaskiewicz** [AWGL/somatic_db#9]
Currently only bioinformatics can do this, need  button in GUI to do it

Might have to be restricted who can do it

**Comment by LauraMcCluskey** [comment]
A case can now be reopened once complete and this will put it back to the previous check. These changes are made in issue9 branch

**Comment by LauraMcCluskey** [comment]
Bug: Unassign doesn't work in this branch- check brackets?

**Comment by Istaisa** [comment]
Completed cases can be reopened only by the person who closed the previous check - check is taken back to pending and assigned to that person. Are there other use cases we'd want for this?

**Comment by erikwaskiewicz** [comment]
fixed in #57
