### ISSUE TITLE
Manual variants added multiple times if page reloaded

### ISSUE THREAD

**Issue by Istaisa** [AWGL/somatic_db#92]
If a manual variant form is submitted and then the page is reloaded, the variant is added again.

**Comment by erikwaskiewicz** [comment]
Need to reload page after form submit (redirect to same page), currently just reloads the context so the form isnt reset
https://github.com/AWGL/somatic_db/blob/e0f39592e59a78bf83cadb71542d3af69f0e42de/analysis/views.py#L443
