### ISSUE TITLE
Illumina fusion naming can lead to multiple fusions with same breakpoints

### ISSUE THREAD

**Issue by Istaisa** [AWGL/somatic_db#96]
Due to the naming conventions from the Illumina app, a fusion with the same breakpoints can be imported with multiple names (e.g. FGFR2-WAC, FGFR2/WAC, FGFR2--WAC) which creates multiple Fusion objects. 

To fix this in the app we need to do two things:
- Modify import.py script so "--" or "/" in a fusion is changed to "-" so all fusions have the same naming conventions and therefore each pair of breakpoints will only be used once
- Check the existing data for instances where there are multiple fusions with identical breakpoints, and link the FusionAnalysis objects to the correctly formatted fusion, then delete the duplicates/triplicates
- Update the existing data so any "--" or "/" are replaced with "-"

**Comment by erikwaskiewicz** [comment]
Fixed in #97
